using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Insurance.Domain.TATA;
public class TATATwoWheelerQuoteRequestDto
{
    public string quote_id { get; set; }
    public string vehicle_idv { get; set; }
    public string q_producer_code { get; set; }
    public string q_producer_email { get; set; }
    public string product_id { get; set; }
    public string product_code { get; set; }
    public string pol_tenure { get; set; }
    public string business_type { get; set; }
    public string business_type_no { get; set; }
    public string proposer_type { get; set; }
    public string plan_type { get; set; }
    public string pol_plan_id { get; set; }
    public string is_posp { get; set; }
    public string q_office_location { get; set; }
    public string sol_id { get; set; }
    public string q_agent_pan { get; set; }
    public string fleet_policy { get; set; }
    public string fleet_code { get; set; }
    public string fleet_name { get; set; }
    public string pol_start_date { get; set; }
    public string pa_owner { get; set; }
    public string pa_owner_tenure { get; set; }
    public string pa_owner_declaration { get; set; }
    public string cpa_start_date { get; set; }
    public string cpa_end_date { get; set; }
    public string driver_age { get; set; }
    public string driver_gender { get; set; }
    public string driver_occupation { get; set; }
    public string claim_last { get; set; }
    public string claim_last_count { get; set; }
    public string claim_last_amount { get; set; }
    public string pre_pol_ncb { get; set; }
    public string no_past_pol { get; set; }
    public string prev_pol_start_date { get; set; }
    public string prev_pol_end_date { get; set; }
    public string prev_pol_type { get; set; }
    public string rtn_invoice { get; set; }
    public string cng_lpg { get; set; }
    public string dep_reimb { get; set; }
    public string ble_tp_start { get; set; }
    public string ble_tp_end { get; set; }
    public string ble_od_start { get; set; }
    public string ble_od_end { get; set; }
    public string special_regno { get; set; }
    public string regno_1 { get; set; }
    public string regno_2 { get; set; }
    public string regno_3 { get; set; }
    public string regno_4 { get; set; }
    public string place_reg { get; set; }
    public string place_reg_no { get; set; }
    public string proposer_pincode { get; set; }
    public string vehicle_make { get; set; }
    public string vehicle_model { get; set; }
    public string vehicle_variant { get; set; }
    public string dor { get; set; }
    public string man_year { get; set; }
    public string manu_month { get; set; }
    public string make_code { get; set; }
    public string model_code { get; set; }
    public string variant_code { get; set; }
    public string veh_plying_city { get; set; }
    public string side_car { get; set; }
    public string side_car_idv { get; set; }
    public string non_electrical_acc { get; set; }
    public string non_electrical_si { get; set; }
    public string non_electrical_des { get; set; }
    public string electrical_acc { get; set; }
    public string electrical_si { get; set; }
    public string electrical_des { get; set; }
    public string cng_lpg_cover { get; set; }
    public string cng_lpg_si { get; set; }
    public string automobile_association_cover { get; set; }
    public string automobile_association_mem_exp_date { get; set; }
    public string automobile_association_mem_no { get; set; }
    public string antitheft_cover { get; set; }
    public string vehicle_blind { get; set; }
    public string own_premises { get; set; }
    public string tppd_discount { get; set; }
    public string voluntary_deductibles { get; set; }
    public string voluntary_amount { get; set; }
    public string voluntary_deductibles_amt { get; set; }
    public string uw_discount { get; set; }
    public string uw_loading { get; set; }
    public string pa_paid { get; set; }
    public string pa_paid_no { get; set; }
    public string pa_paid_si { get; set; }
    public string pa_unnamed { get; set; }
    public string pa_unnamed_no { get; set; }
    public string pa_unnamed_si { get; set; }
    public string dep_reimburse { get; set; }
    public string dep_reimburse_claims { get; set; }
    public string dep_reimburse_deductible { get; set; }
    public string return_invoice { get; set; }
    public string consumbale_expense { get; set; }
    public string add_towing { get; set; }
    public string add_towing_amount { get; set; }
    public string rsa { get; set; }
    public string emg_med_exp { get; set; }
    public string emg_med_exp_si { get; set; }
    public string ll_paid { get; set; }
    public string ll_paid_no { get; set; }
    public string ll_emp { get; set; }
    public string ll_emp_no { get; set; }
    public string add_tppd { get; set; }
    public string add_tppd_si { get; set; }
    public string add_pa_owner { get; set; }
    public string add_pa_owner_si { get; set; }
    public string add_pa_unnamed { get; set; }
    public string add_pa_unnamed_si { get; set; }
    public string driving_tution { get; set; }
    public string vehicle_trails_racing { get; set; }
    public string event_name { get; set; }
    public string promoter_name { get; set; }
    public string event_from_date { get; set; }
    public string event_to_date { get; set; }
    public string ext_racing { get; set; }
    public string imported_veh_without_cus_duty { get; set; }
    public string fibre_fuel_tank { get; set; }
    public string loss_accessories { get; set; }
    public string loss_accessories_idv { get; set; }
    public string geography_extension { get; set; }
    public string geography_extension_bang { get; set; }
    public string geography_extension_bhutan { get; set; }
    public string geography_extension_lanka { get; set; }
    public string geography_extension_maldives { get; set; }
    public string geography_extension_nepal { get; set; }
    public string geography_extension_pak { get; set; }
    public string __finalize { get; set; }
}
