CREATE TABLE [dbo].[Identity_UserDetail] (
    [Id]                                VARCHAR (100)  CONSTRAINT [DF_Identity_UserDetail_Id] DEFAULT (newid()) NOT NULL,
    [UserId]                            VARCHAR (100)  NOT NULL,
    [DateofBirth]                       VARCHAR (20)   NULL,
    [Gender]                            VARCHAR (20)   NULL,
    [AlternateContactNo]                VARCHAR (10)   NULL,
    [AadhaarNumber]                     VARCHAR (12)   NULL,
    [PAN]                               VARCHAR (10)   NULL,
    [IsNameDifferentOnDocument]         BIT            CONSTRAINT [DF_Identity_UserDetail_IsNameDifferentOnDocument] DEFAULT ((0)) NULL,
    [AliasName]                         VARCHAR (100)  NULL,
    [EducationQualificationTypeId]      VARCHAR (100)  NULL,
    [InsuranceSellingExperienceRangeId] VARCHAR (100)  NULL,
    [InsuranceProductsofInterestTypeId] VARCHAR (100)  NULL,
    [POSPSourceMode]                    BIT            CONSTRAINT [DF_Identity_UserDetail_POSPSourceMode] DEFAULT ((1)) NULL,
    [POSPSourceTypeId]                  VARCHAR (100)  NULL,
    [SourcedByUserId]                   VARCHAR (100)  NULL,
    [ServicedByUserId]                  VARCHAR (100)  NULL,
    [NOCAvailable]                      VARCHAR (100)  NULL,
    [ProfilePictureID]                  VARCHAR (500)  NULL,
    [ProfilePictureFileName]            VARCHAR (500)  NULL,
    [ProfilePictureStoragePath]         VARCHAR (MAX)  NULL,
    [IsActive]                          BIT            CONSTRAINT [DF_Identity_UserDetail_IsActive] DEFAULT ((1)) NULL,
    [CreatedBy]                         VARCHAR (50)   NULL,
    [CreatedOn]                         DATETIME       CONSTRAINT [DF_Identity_UserDetail_CreatedOn] DEFAULT (getdate()) NULL,
    [UpdatedBy]                         VARCHAR (50)   NULL,
    [UpdatedOn]                         DATETIME       NULL,
    [NameDifferentDocument]             VARCHAR (1000) NULL,
    [NameDifferentDocumentFilePath]     VARCHAR (1000) NULL,
    [DocumentId]                        VARCHAR (100)  NULL,
    [IsSelling]                         VARCHAR (10)   NULL,
    [PreSale]                           VARCHAR (200)  NULL,
    [PostSale]                          VARCHAR (200)  NULL,
    [Marketing]                         VARCHAR (200)  NULL,
    [Claim]                             VARCHAR (200)  NULL,
    [RelationshipManager]               VARCHAR (100)  NULL,
    [AssistedBUId]                      VARCHAR (200)  NULL,
    CONSTRAINT [PK_Identity_UserDetail_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);



