CREATE TABLE [MOTOR].[Chola_FinancierMaster] (
    [TXT_FINANCIER_CD]      INT            NULL,
    [TXT_FINANCIER_NAME]    NVARCHAR (MAX) NULL,
    [TXT_FINANCIER_ADDRESS] INT            NULL,
    [TXT_ACTIVE_FLAG]       NVARCHAR (MAX) NULL,
    [DAT_INSERT_DATE]       DATETIME2 (7)  NULL,
    [DAT_MODIFY_DATE]       NVARCHAR (MAX) NULL,
    [NUM_INSERT_TRANS_ID]   BIGINT         NULL,
    [NUM_MODIFY_TRANS_ID]   NVARCHAR (MAX) NULL,
    [TXT_REFERENCE_KEY]     INT            NULL,
    [TXT_COMMACT_FLAG]      NVARCHAR (MAX) NULL
);

