CREATE TABLE [MOTOR].[HDFC_CV_VehicleMaster] (
    [F1]                        NVARCHAR (255) NULL,
    [VEHICLECLASSCODE]          NVARCHAR (255) NULL,
    [MANUFACTURER]              NVARCHAR (255) NULL,
    [VEHICLEMODELCODE]          NVARCHAR (255) NULL,
    [VEHICLEMODEL]              NVARCHAR (255) NULL,
    [NUMBEROFWHEELS]            NVARCHAR (255) NULL,
    [CUBICCAPACITY]             NVARCHAR (255) NULL,
    [GROSSVEHICLEWEIGHT]        NVARCHAR (255) NULL,
    [SEATINGCAPACITY]           NVARCHAR (255) NULL,
    [CARRYINGCAPACITY]          NVARCHAR (255) NULL,
    [BODYTYPECODE]              NVARCHAR (255) NULL,
    [TXT_OBSOLETE_FLAG]         NVARCHAR (255) NULL,
    [NUM_VEHICLE_SUBCLASS_CODE] FLOAT (53)     NULL,
    [ACTIVE_FLAG]               NVARCHAR (255) NULL,
    [TXT_FUEL]                  NVARCHAR (255) NULL,
    [TXT_SEGMENTTYPE]           NVARCHAR (255) NULL,
    [TXT_VARIANT]               NVARCHAR (255) NULL,
    [MANUFACTURERCODE]          NVARCHAR (255) NULL,
    [NUM_ENGNO_LENGTH]          FLOAT (53)     NULL,
    [NUM_CHASSISNO_LENGTH]      FLOAT (53)     NULL,
    [SUB_MODEL_GROUP]           NVARCHAR (255) NULL
);

