CREATE TABLE [MOTOR].[HDFC_CV_RTOMaster] (
    [TXT_RTO_LOCATION_DESC]     NVARCHAR (255) NULL,
    [TXT_RTO_LOCATION_CODE]     NVARCHAR (255) NULL,
    [NUM_VEHICLE_CLASS_CODE]    FLOAT (53)     NULL,
    [TXT_REGISTRATION_ZONE]     NVARCHAR (255) NULL,
    [NUM_VEHICLE_SUBCLASS_CODE] FLOAT (53)     NULL,
    [NUM_STATE_CODE]            FLOAT (53)     NULL,
    [RTOId]                     VARCHAR (100)  NULL
);

