CREATE TABLE [MOTOR].[Oriental_IDVMaster] (
    [CITY_NAME]           NVARCHAR (255) NULL,
    [MANUFACTURER_NAME]   NVARCHAR (255) NULL,
    [PRODUCT_NAME]        NVARCHAR (255) NULL,
    [MODEL_NAME]          NVARCHAR (255) NULL,
    [VARIANT_NAME]        NVARCHAR (255) NULL,
    [INLIAS_VEHICLE_CODE] VARCHAR (10)   NULL,
    [CUBIC_CAPACITY]      VARCHAR (10)   NULL,
    [SEATING_CAPACITY]    VARCHAR (10)   NULL,
    [FUEL_TYPE]           VARCHAR (50)   NULL,
    [EX_PRICE]            VARCHAR (10)   NULL,
    [UPTO_6_MONTHS]       VARCHAR (10)   NULL,
    [UPTO_1_YEAR]         VARCHAR (10)   NULL,
    [UPTO_2_YEAR]         VARCHAR (10)   NULL,
    [UPTO_3_YEAR]         VARCHAR (10)   NULL,
    [UPTO_4_YEAR]         VARCHAR (10)   NULL,
    [UPTO_5_YEAR]         VARCHAR (10)   NULL,
    [UPTO_6_YEAR]         VARCHAR (10)   NULL,
    [UPTO_7_YEAR]         VARCHAR (10)   NULL,
    [UPTO_8_YEAR]         VARCHAR (10)   NULL,
    [UPTO_9_YEAR]         VARCHAR (10)   NULL,
    [UPTO_10_YEAR]        VARCHAR (10)   NULL,
    [UPTO_11_YEAR]        VARCHAR (10)   NULL,
    [UPTO_12_YEAR]        VARCHAR (10)   NULL,
    [UPTO_13_YEAR]        VARCHAR (10)   NULL,
    [UPTO_14_YEAR]        VARCHAR (10)   NULL,
    [UPTO_15_YEAR]        VARCHAR (10)   NULL,
    [CreatedBy]           VARCHAR (50)   DEFAULT ((1)) NULL,
    [CreatedOn]           DATETIME       DEFAULT (getdate()) NULL,
    [UpdatedBy]           VARCHAR (50)   NULL,
    [UpdatedOn]           DATETIME       NULL
);

