CREATE TABLE [MOTOR].[UIIC_PinCode] (
    [   SL NO]         NVARCHAR (255) NULL,
    [STATE CODE]       NVARCHAR (255) NULL,
    [CITYDISTRICT CD]  NVARCHAR (255) NULL,
    [PINCODE]          NVARCHAR (255) NULL,
    [PINCODE LOCALITY] NVARCHAR (255) NULL
);

