CREATE TABLE [MOTOR].[UIIC_RTOMaster] (
    [S No]                   FLOAT (53)     NULL,
    [VEHICLECLASSDESC]       NVARCHAR (255) NULL,
    [TXT_STATE]              NVARCHAR (255) NULL,
    [TXT_RTO_LOCATION_CODE]  NVARCHAR (255) NULL,
    [TXT_RTO_LOCATION_DESC]  NVARCHAR (255) NULL,
    [TXT_RTO_LOCATION_CODE1] NVARCHAR (255) NULL,
    [TXT_REGISTRATION_ZONE]  NVARCHAR (255) NULL,
    [RTOId]                  VARCHAR (50)   NULL
);

