CREATE TABLE [MOTOR].[UIIC_SalutationMaster] (
    [S No]          NVARCHAR (255) NULL,
    [SALUTATION ID] NVARCHAR (255) NULL,
    [SALUTATION]    NVARCHAR (255) NULL,
    [CATEGORY TYPE] NVARCHAR (255) NULL
);

