CREATE TABLE [dbo].[CVVehiclesMMVData] (
    [F]                     NVARCHAR (255) NULL,
    [Make]                  NVARCHAR (255) NULL,
    [Model]                 NVARCHAR (255) NULL,
    [Variant]               NVARCHAR (255) NULL,
    [Body Type]             NVARCHAR (255) NULL,
    [Seating Capacity]      FLOAT (53)     NULL,
    [Power]                 FLOAT (53)     NULL,
    [Cubic Capacity]        FLOAT (53)     NULL,
    [Grosss Vehicle Weight] FLOAT (53)     NULL,
    [Fuel Type]             NVARCHAR (255) NULL,
    [No Of Wheels]          FLOAT (53)     NULL,
    [Abs]                   NVARCHAR (255) NULL,
    [Air Bags]              NVARCHAR (255) NULL,
    [Length]                FLOAT (53)     NULL,
    [Ex Showroom Price]     FLOAT (53)     NULL,
    [Price Year]            FLOAT (53)     NULL,
    [Production]            NVARCHAR (255) NULL,
    [Manufacturing]         NVARCHAR (255) NULL,
    [Vehicle Type]          NVARCHAR (255) NULL,
    [Vehicle Category]      NVARCHAR (255) NULL,
    [Vehicle Sub Category]  NVARCHAR (255) NULL,
    [MakeId]                VARCHAR (50)   NULL,
    [ModelId]               VARCHAR (50)   NULL,
    [VariantId]             VARCHAR (50)   NULL,
    [VehicleTypeId]         VARCHAR (50)   NULL,
    [FuleId]                VARCHAR (50)   NULL,
    [CVSubCategoryId]       INT            NULL
);

