CREATE TABLE [MOTER].[UIIC_CityMaster] (
    [   SL NO]        NVARCHAR (255) NULL,
    [STATE CD]        NVARCHAR (255) NULL,
    [CITYDISTRICT CD] NVARCHAR (255) NULL,
    [CITY DISTRICT]   NVARCHAR (255) NULL
);

